# Generated by Django 4.2.5 on 2023-10-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='data',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=2),
        ),
    ]
