# Generated by Django 4.2.5 on 2023-10-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_userinfo_data_alter_userinfo_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
