# Generated by Django 4.2.5 on 2023-10-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=12),
        ),
    ]
